Class HL7Demo.Data.FacilityQM Extends %Persistent [ ProcedureBlock ]
{

Property Accidentalcutsandtearsfrommedicaltreatment As %String(MAXLEN = 500);

Property Address1 As %String(MAXLEN = 500);

Property Address2 As %String(MAXLEN = 500);

Property Address3 As %String(MAXLEN = 500);

Property Awoundthatsplitsopenaftersurgery As %String(MAXLEN = 500);

Property Breathingfailureaftersurgery As %String(MAXLEN = 500);

Property City As %String(MAXLEN = 500);

Property Collapsedlungduetomedicaltreatment As %String(MAXLEN = 500);

Property CountyName As %String(MAXLEN = 500);

Property Deathaftersurgerytorepairaweaknessintheabdominalaorta As %String(MAXLEN = 500);

Property Deathfromserioustreatablecomplicationsaftersurgery As %String(MAXLEN = 500);

Property Deathsafteradmissionforbrokenhip As %String(MAXLEN = 500);

Property DeathsfromCertainConditions As %String(MAXLEN = 500);

Property FootnoteAccidentalcutsandtearsfrommedicaltreatment As %String(MAXLEN = 500);

Property FootnoteAwoundthatsplitsopenaftersurgery As %String(MAXLEN = 500);

Property FootnoteBreathingfailureaftersurgery As %String(MAXLEN = 500);

Property FootnoteCollapsedlungduetomedicaltreatment As %String(MAXLEN = 500);

Property FootnoteDeathaftersurgerytorepairaweaknessintheabdominalaorta As %String(MAXLEN = 500);

Property FootnoteDeathfromserioustreatablecomplicationsaftersurgery As %String(MAXLEN = 500);

Property FootnoteDeathsafteradmissionforbrokenhip As %String(MAXLEN = 500);

Property FootnoteDeathsfromCertainConditions As %String(MAXLEN = 500);

Property FootnoteSeriousComplications As %String(MAXLEN = 500);

Property FootnoteSeriousbloodclotsaftersurgery As %String(MAXLEN = 500);

Property HigherEstimateAccidentalcutsandtearsfrommedicaltreatment As %String(MAXLEN = 500);

Property HigherEstimateAwoundthatsplitsopenaftersurgery As %String(MAXLEN = 500);

Property HigherEstimateBreathingfailureaftersurgery As %String(MAXLEN = 500);

Property HigherEstimateCollapsedlungduetomedicaltreatment As %String(MAXLEN = 500);

Property HigherEstimateDeathaftersurgerytorepairaweaknessintheabdominalaorta As %String(MAXLEN = 500);

Property HigherEstimateDeathfromserioustreatablecomplicationsaftersurgery As %String(MAXLEN = 500);

Property HigherEstimateDeathsafteradmissionforbrokenhip As %String(MAXLEN = 500);

Property HigherEstimateDeathsfromCertainConditions As %String(MAXLEN = 500);

Property HigherEstimateSeriousComplications As %String(MAXLEN = 500);

Property HigherEstimateSeriousbloodclotsaftersurgery As %String(MAXLEN = 500);

Property HospitalName As %String(MAXLEN = 500);

Property LowerEstimateAccidentalcutsandtearsfrommedicaltreatment As %String(MAXLEN = 500);

Property LowerEstimateAwoundthatsplitsopenaftersurgery As %String(MAXLEN = 500);

Property LowerEstimateBreathingfailureaftersurgery As %String(MAXLEN = 500);

Property LowerEstimateCollapsedlungduetomedicaltreatment As %String(MAXLEN = 500);

Property LowerEstimateDeathaftersurgerytorepairaweaknessintheabdominalaorta As %String(MAXLEN = 500);

Property LowerEstimateDeathfromserioustreatablecomplicationsaftersurgery As %String(MAXLEN = 500);

Property LowerEstimateDeathsafteradmissionforbrokenhip As %String(MAXLEN = 500);

Property LowerEstimateDeathsfromCertainConditions As %String(MAXLEN = 500);

Property LowerEstimateSeriousComplications As %String(MAXLEN = 500);

Property LowerEstimateSeriousbloodclotsaftersurgery As %String(MAXLEN = 500);

Property NumberofPatientsAccidentalcutsandtearsfrommedicaltreatment As %String(MAXLEN = 500);

Property NumberofPatientsAwoundthatsplitsopenaftersurgery As %String(MAXLEN = 500);

Property NumberofPatientsBreathingfailureaftersurgery As %String(MAXLEN = 500);

Property NumberofPatientsCollapsedlungduetomedicaltreatment As %String(MAXLEN = 500);

Property NumberofPatientsDeathaftersurgerytorepairaweaknessintheabdominalaorta As %String(MAXLEN = 500);

Property NumberofPatientsDeathfromserioustreatablecomplicationsaftersurgery As %String(MAXLEN = 500);

Property NumberofPatientsDeathsafteradmissionforbrokenhip As %String(MAXLEN = 500);

Property NumberofPatientsDeathsfromCertainConditions As %String(MAXLEN = 500);

Property NumberofPatientsSeriousComplications As %String(MAXLEN = 500);

Property NumberofPatientsSeriousbloodclotsaftersurgery As %String(MAXLEN = 500);

Property PhoneNumber As %String(MAXLEN = 500);

Property ProviderNumber As %String(MAXLEN = 500);

Property RateAccidentalcutsandtearsfrommedicaltreatment As %String(MAXLEN = 500);

Property RateAwoundthatsplitsopenaftersurgery As %String(MAXLEN = 500);

Property RateBreathingfailureaftersurgery As %String(MAXLEN = 500);

Property RateCollapsedlungduetomedicaltreatment As %String(MAXLEN = 500);

Property RateDeathaftersurgerytorepairaweaknessintheabdominalaorta As %String(MAXLEN = 500);

Property RateDeathfromserioustreatablecomplicationsaftersurgery As %String(MAXLEN = 500);

Property RateDeathsafteradmissionforbrokenhip As %String(MAXLEN = 500);

Property RateDeathsfromCertainConditions As %String(MAXLEN = 500);

Property RateSeriousComplications As %String(MAXLEN = 500);

Property RateSeriousbloodclotsaftersurgery As %String(MAXLEN = 500);

Property SeriousComplications As %String(MAXLEN = 500);

Property Seriousbloodclotsaftersurgery As %String(MAXLEN = 500);

Property State As %String(MAXLEN = 500);

Property ZIPCode As %String(MAXLEN = 500);

<Storage name="Default">
<Data name="FacilityQMDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Accidentalcutsandtearsfrommedicaltreatment</Value>
</Value>
<Value name="3">
<Value>Address1</Value>
</Value>
<Value name="4">
<Value>Address2</Value>
</Value>
<Value name="5">
<Value>Address3</Value>
</Value>
<Value name="6">
<Value>Awoundthatsplitsopenaftersurgery</Value>
</Value>
<Value name="7">
<Value>Breathingfailureaftersurgery</Value>
</Value>
<Value name="8">
<Value>City</Value>
</Value>
<Value name="9">
<Value>Collapsedlungduetomedicaltreatment</Value>
</Value>
<Value name="10">
<Value>CountyName</Value>
</Value>
<Value name="11">
<Value>Deathaftersurgerytorepairaweaknessintheabdominalaorta</Value>
</Value>
<Value name="12">
<Value>Deathfromserioustreatablecomplicationsaftersurgery</Value>
</Value>
<Value name="13">
<Value>Deathsafteradmissionforbrokenhip</Value>
</Value>
<Value name="14">
<Value>DeathsfromCertainConditions</Value>
</Value>
<Value name="15">
<Value>FootnoteAccidentalcutsandtearsfrommedicaltreatment</Value>
</Value>
<Value name="16">
<Value>FootnoteAwoundthatsplitsopenaftersurgery</Value>
</Value>
<Value name="17">
<Value>FootnoteBreathingfailureaftersurgery</Value>
</Value>
<Value name="18">
<Value>FootnoteCollapsedlungduetomedicaltreatment</Value>
</Value>
<Value name="19">
<Value>FootnoteDeathaftersurgerytorepairaweaknessintheabdominalaorta</Value>
</Value>
<Value name="20">
<Value>FootnoteDeathfromserioustreatablecomplicationsaftersurgery</Value>
</Value>
<Value name="21">
<Value>FootnoteDeathsafteradmissionforbrokenhip</Value>
</Value>
<Value name="22">
<Value>FootnoteDeathsfromCertainConditions</Value>
</Value>
<Value name="23">
<Value>FootnoteSeriousComplications</Value>
</Value>
<Value name="24">
<Value>FootnoteSeriousbloodclotsaftersurgery</Value>
</Value>
<Value name="25">
<Value>HigherEstimateAccidentalcutsandtearsfrommedicaltreatment</Value>
</Value>
<Value name="26">
<Value>HigherEstimateAwoundthatsplitsopenaftersurgery</Value>
</Value>
<Value name="27">
<Value>HigherEstimateBreathingfailureaftersurgery</Value>
</Value>
<Value name="28">
<Value>HigherEstimateCollapsedlungduetomedicaltreatment</Value>
</Value>
<Value name="29">
<Value>HigherEstimateDeathaftersurgerytorepairaweaknessintheabdominalaorta</Value>
</Value>
<Value name="30">
<Value>HigherEstimateDeathfromserioustreatablecomplicationsaftersurgery</Value>
</Value>
<Value name="31">
<Value>HigherEstimateDeathsafteradmissionforbrokenhip</Value>
</Value>
<Value name="32">
<Value>HigherEstimateDeathsfromCertainConditions</Value>
</Value>
<Value name="33">
<Value>HigherEstimateSeriousComplications</Value>
</Value>
<Value name="34">
<Value>HigherEstimateSeriousbloodclotsaftersurgery</Value>
</Value>
<Value name="35">
<Value>HospitalName</Value>
</Value>
<Value name="36">
<Value>LowerEstimateAccidentalcutsandtearsfrommedicaltreatment</Value>
</Value>
<Value name="37">
<Value>LowerEstimateAwoundthatsplitsopenaftersurgery</Value>
</Value>
<Value name="38">
<Value>LowerEstimateBreathingfailureaftersurgery</Value>
</Value>
<Value name="39">
<Value>LowerEstimateCollapsedlungduetomedicaltreatment</Value>
</Value>
<Value name="40">
<Value>LowerEstimateDeathaftersurgerytorepairaweaknessintheabdominalaorta</Value>
</Value>
<Value name="41">
<Value>LowerEstimateDeathfromserioustreatablecomplicationsaftersurgery</Value>
</Value>
<Value name="42">
<Value>LowerEstimateDeathsafteradmissionforbrokenhip</Value>
</Value>
<Value name="43">
<Value>LowerEstimateDeathsfromCertainConditions</Value>
</Value>
<Value name="44">
<Value>LowerEstimateSeriousComplications</Value>
</Value>
<Value name="45">
<Value>LowerEstimateSeriousbloodclotsaftersurgery</Value>
</Value>
<Value name="46">
<Value>NumberofPatientsAccidentalcutsandtearsfrommedicaltreatment</Value>
</Value>
<Value name="47">
<Value>NumberofPatientsAwoundthatsplitsopenaftersurgery</Value>
</Value>
<Value name="48">
<Value>NumberofPatientsBreathingfailureaftersurgery</Value>
</Value>
<Value name="49">
<Value>NumberofPatientsCollapsedlungduetomedicaltreatment</Value>
</Value>
<Value name="50">
<Value>NumberofPatientsDeathaftersurgerytorepairaweaknessintheabdominalaorta</Value>
</Value>
<Value name="51">
<Value>NumberofPatientsDeathfromserioustreatablecomplicationsaftersurgery</Value>
</Value>
<Value name="52">
<Value>NumberofPatientsDeathsafteradmissionforbrokenhip</Value>
</Value>
<Value name="53">
<Value>NumberofPatientsDeathsfromCertainConditions</Value>
</Value>
<Value name="54">
<Value>NumberofPatientsSeriousComplications</Value>
</Value>
<Value name="55">
<Value>NumberofPatientsSeriousbloodclotsaftersurgery</Value>
</Value>
<Value name="56">
<Value>PhoneNumber</Value>
</Value>
<Value name="57">
<Value>ProviderNumber</Value>
</Value>
<Value name="58">
<Value>RateAccidentalcutsandtearsfrommedicaltreatment</Value>
</Value>
<Value name="59">
<Value>RateAwoundthatsplitsopenaftersurgery</Value>
</Value>
<Value name="60">
<Value>RateBreathingfailureaftersurgery</Value>
</Value>
<Value name="61">
<Value>RateCollapsedlungduetomedicaltreatment</Value>
</Value>
<Value name="62">
<Value>RateDeathaftersurgerytorepairaweaknessintheabdominalaorta</Value>
</Value>
<Value name="63">
<Value>RateDeathfromserioustreatablecomplicationsaftersurgery</Value>
</Value>
<Value name="64">
<Value>RateDeathsafteradmissionforbrokenhip</Value>
</Value>
<Value name="65">
<Value>RateDeathsfromCertainConditions</Value>
</Value>
<Value name="66">
<Value>RateSeriousComplications</Value>
</Value>
<Value name="67">
<Value>RateSeriousbloodclotsaftersurgery</Value>
</Value>
<Value name="68">
<Value>SeriousComplications</Value>
</Value>
<Value name="69">
<Value>Seriousbloodclotsaftersurgery</Value>
</Value>
<Value name="70">
<Value>State</Value>
</Value>
<Value name="71">
<Value>ZIPCode</Value>
</Value>
</Data>
<DataLocation>^HL7Demo.Data.FacilityQMD</DataLocation>
<DefaultData>FacilityQMDefaultData</DefaultData>
<ExtentSize>100000</ExtentSize>
<IdLocation>^HL7Demo.Data.FacilityQMD</IdLocation>
<IndexLocation>^HL7Demo.Data.FacilityQMI</IndexLocation>
<StreamLocation>^HL7Demo.Data.FacilityQMS</StreamLocation>
<Type>%Library.CacheStorage</Type>
</Storage>
}

