shed -v -ns hl7demo post HL7Demo.Data.Allergens.cls
shed -v -ns hl7demo post HL7Demo.Data.CMS30DX.cls
shed -v -ns hl7demo post HL7Demo.Data.CommomLabOrders.cls
shed -v -ns hl7demo post HL7Demo.Data.CommonLabOrders.cls
shed -v -ns hl7demo post HL7Demo.Data.CommonLabResults.cls
shed -v -ns hl7demo post HL7Demo.Data.FacilityQM.cls
shed -v -ns hl7demo post HL7Demo.Data.Medications.cls
shed -v -ns hl7demo post HL7Demo.Data.People.cls
shed -v -ns hl7demo post HL7Demo.Data.Providers.cls
shed -v -ns hl7demo post HL7Demo.Data.VitalSignResultCodes.cls
shed -v -ns hl7demo post HL7Demo.MsgSender.cls
shed -v -ns hl7demo post HL7Demo.PeopleDataLoader.cls
shed -v -ns hl7demo post HL7Demo.Test1.cls
shed -v -ns hl7demo post HL7Demo.Util.cls
